# Generated by Django 4.0.4 on 2022-04-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.author')),
            ],
        ),
        migrations.CreateModel(
            name='Caculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number1', models.IntegerField()),
                ('Number2', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'ordering': ['Number1'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_Cua_Hang', models.CharField(max_length=500)),
                ('Ma_Cua_Hang', models.CharField(max_length=50)),
                ('Dia_Chi', models.CharField(max_length=500)),
                ('Ngay_Tao', models.DateTimeField(verbose_name='publish date')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('Ten_Khach_Hang', models.CharField(max_length=200)),
                ('Ma_Khach_Hang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_San_Pham', models.CharField(max_length=500)),
                ('Ma_San_Pham', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.book')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfor',
            fields=[
                ('CustomerInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('CMND', models.CharField(max_length=500)),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.customer')),
            ],
            options={
                'ordering': ['CustomerInfoId'],
            },
        ),
    ]
