# Generated by Django 4.0.4 on 2022-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=4)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
